### ISSUE TITLE
ERROR Plugin.disablePlugin is not a function

### ISSUE THREAD

**Issue by alejandrosc** [release-it/bumper#2]
Hi guys, Im getting this error:

> extension@3.2.0 release /home/alejandro/apps/durango/extension
> release-it "minor"

```log
ERROR Plugin.disablePlugin is not a function
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! extension@3.2.0 release: `release-it "minor"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the extension@3.2.0 release script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/alejandro/.npm/_logs/2019-06-03T19_35_30_575Z-debug.log
```

I want to update a manifest file, but I think the program is throwing errors about this plugin

```json
{
	"git": {
		"requireCleanWorkingDir": false,
		"requireUpstream": true,
		"requireCommits": true,
		"addUntrackedFiles": false,
		"commit": true,
		"commitMessage": "Release ${version}",
		"commitArgs": "-S",
		"tag": true,
		"tagName": "v${version}",
		"tagAnnotation": "Release ${version}",
		"tagArgs": "-s",
		"push": true,
		"pushArgs": "--follow-tags",
		"pushRepo": "origin"
	},
	"npm": {
		"publish": false
	},
	"plugins": {
		"@release-it/bumper": {
			"in": { "file": "manifest.json" },
			"out": { "file": "manifest.json" }
		},
		"@release-it/conventional-changelog": {
			"infile": "CHANGELOG.md"
		}
	}
}
```

```log
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/home/alejandro/.nvm/versions/node/v12.2.0/bin/node',
1 verbose cli   '/home/alejandro/.nvm/versions/node/v12.2.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'release',
1 verbose cli   'minor'
1 verbose cli ]
2 info using npm@6.9.0
3 info using node@v12.2.0
4 verbose run-script [ 'prerelease', 'release', 'postrelease' ]
5 info lifecycle extension@3.2.0~prerelease: extension@3.2.0
6 info lifecycle extension@3.2.0~release: extension@3.2.0
7 verbose lifecycle extension@3.2.0~release: unsafe-perm in lifecycle true
8 verbose lifecycle extension@3.2.0~release: PATH: /home/alejandro/.nvm/versions/node/v12.2.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/alejandro/apps/durango/extension/node_modules/.bin:/home/alejandro/.nvm/versions/node/v12.2.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle extension@3.2.0~release: CWD: /home/alejandro/apps/durango/extension
10 silly lifecycle extension@3.2.0~release: Args: [ '-c', 'release-it "minor"' ]
11 silly lifecycle extension@3.2.0~release: Returned: code: 1  signal: null
12 info lifecycle extension@3.2.0~release: Failed to exec release script
13 verbose stack Error: extension@3.2.0 release: `release-it "minor"`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/home/alejandro/.nvm/versions/node/v12.2.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:196:13)
13 verbose stack     at ChildProcess.<anonymous> (/home/alejandro/.nvm/versions/node/v12.2.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:196:13)
13 verbose stack     at maybeClose (internal/child_process.js:1011:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:268:5)
14 verbose pkgid extension@3.2.0
15 verbose cwd /home/alejandro/apps/durango/extension
16 verbose Linux 5.0.0-15-generic
17 verbose argv "/home/alejandro/.nvm/versions/node/v12.2.0/bin/node" "/home/alejandro/.nvm/versions/node/v12.2.0/bin/npm" "run" "release" "minor"
18 verbose node v12.2.0
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 1
22 error extension@3.2.0 release: `release-it "minor"`
22 error Exit status 1
23 error Failed at the extension@3.2.0 release script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

Environment:

Ubuntu 19.04 (Kernel linux 5)
npm: 6.9.0
node: v12.2.0
release-it: 12.2.2
@release-it/bumper: 1.0.2
@release-it/conventional-changelog: 1.1.0

Any ideas??, thanks!!

**Comment by webpro** [comment]
Should be fixed in v1.0.3. Please let me know if it works for you.
